name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
repository: https://github.com/flutter/packages/tree/main/packages/video_player/video_player
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.6.1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: video_player_android
      ios:
        default_package: video_player_avfoundation
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  video_player_platform_interface: ">=6.1.0 <7.0.0"
  video_player_web:
     git:
       url: https://github.com/ologunB/video_player.git
       ref: main
       path: video_player_web
  video_player_android:
     git:
       url: https://github.com/ologunB/video_player.git
       ref: main
       path: video_player_android
  video_player_avfoundation:
     git:
       url: https://github.com/ologunB/video_player.git
       ref: main
       path: video_player_avfoundation

dev_dependencies:
  flutter_test:
    sdk: flutter
